### PR TITLE
DE-263 - CI/CD documentation

### PR DESCRIPTION
**Pull request by andresmoschini**
Hi @paangaflo, @Cromeror, @maurocardinali, @cbernat, @jcamposmk, @ck-makingsense, and @GusBaamonde,

Here I am trying to document how does the new CI, CD, and distribution works in this project.

I think that this approach is very similar to what we are doing with docker images, but it applies to frontend projects and takes advantage of browser cache and Cloudflare cache, I think that we should move all the editors to this new approach and also other front-end projects:

* [UI Library](https://github.com/FromDoppler/Doppler-UI-System)
* [Doppler WebApp](https://github.com/FromDoppler/doppler-webapp)
* [Relay WebApp](https://github.com/FromDoppler/relay-webapp)
* [Templates Editor (MSEditor)](https://github.com/MakingSense/MSEditor/)
* [Forms Editor](https://github.com/MakingSense/doppler-forms-editor)
* [Forms Generator](https://github.com/MakingSense/doppler-forms-generator)
* Something else?

It would really simplify our development and deployment process and it would improve the performance because of a better cache usage. 

It is not easy to explain these kinds of things, I would really appreciate your feedback, could you review it?

Let me know if you have any doubts.

### CODE REVIEW

**Comment by andresmoschini** [comment]
Remember that you can use the _rich diff_ button to see the differences in the markdown result:

image

Or you can see the result document here: https://github.com/andresmoschini/unlayer-editor/blob/DE-263-documentation/README.md

**Review by maurocardinali — COMMENTED** [review]
Really really useful readme! Great job! 🚀

**Comment by paangaflo** [comment]
Cool. 🚀

**Comment by jcamposmk** [comment]
:+1: I think it's great. It will be of great help for new people who start the project.

**Pull request merged**
