### PR TITLE
[DE-298] Recibir un parámetro arbitrario en el init y renderizarlo en una custom tool

### PR DESCRIPTION
**Pull request by Cromeror**
Se agrega un modulo compartido que se inicializa desde el unlayer.init

https://vimeo.com/604894658/7e6a9eb153

### CODE REVIEW

**Comment by andresmoschini** [comment]
Do you think that is there a way to share the token a single time with all the tools?

**Comment by Cromeror** [comment]
> Do you think that is there a way to share the token a single time with all the tools?

Nop, looking in the documentation of a layer I see that they do not thinking passing global data to all the components, each component treats it separately.

**Comment by Cromeror** [comment]
> > Do you think that is there a way to share the token a single time with all the tools?
> 
> Maybe you can have a singleton module with the token and inject the value in the `customJS` property:
> 
> ```js
>   // . . .
>   const UnlayerOptionsExtended = {
>     mergeTagsConfig: {
>       sort: false,
>     },
>     mergeTags: mergeTags,
>     user: userExtend,
>     customJS: [
>       `${window.location.href}/customJs/index.js`,
>       `window.sharedSingletonModule.dopplerJwtToken = \'xxx\';`
>     ],
>     tools: {
>       // . . .
> ```
> 
> Or better yet:
> 
> ```js
>   // . . .
>   const UnlayerOptionsExtended = {
>     mergeTagsConfig: {
>       sort: false,
>     },
>     mergeTags: mergeTags,
>     user: userExtend,
>     customJS: [
>       `${window.location.href}/customJs/index.js`,
>       `window.dopplerAuthentication.initialize({
>          token: 'xxx',
>          renovationDelayInSeconds: 1200,
>          renovationUrl: `https://apis.fromdoppler.com/jwt/renew`
>        });`
>     ],
>     tools: {
>       // . . .
> ```

I can't inject external data into unlayer's windows variable.

**Comment by andresmoschini** [comment]
❤️

**Comment by andresmoschini** [comment]
:shipit:

**Pull request merged**
